### ISSUE TITLE
Hello, can you tell me how to compile v8js?

### ISSUE THREAD

**Issue by 54huige** [pinepain/php-v8#112]
Hello, can you tell me how to compile v8js?

**Comment by pinepain** [comment]
Hi, sorry `php-v8` and `v8js` are different extensions, so I'm not quite good with `v8js` building process, however it [Dockerfile.travis](https://github.com/phpv8/v8js/blob/php7/Dockerfile.travis) demonstrates how to build extension.

**Comment by 54huige** [comment]
Excuse me? php-v8. How to compile on Windows? his demand is very strong.

**Comment by pinepain** [comment]
php-v8 doesn't officially support Windows and I've never had it working there. In short, you need to compile libv8 there first and then php-v8 itself. Honestly, I'm not a Windows user so I can't provide any further guidance how to compile extension there. It should be like other php extensions, I guess, however, as said before, php-v8 was written without windows support in mind, so even if you find out how to build it, be aware that it may fail because of some incompatibility, if any. Good luck with that! Feels free to write back with your outcome.

Also, if it's feasible, you may try to run php-v8 in docker even on windows, sure, if your use case match this flow.

Cheers!
